# -*- coding: utf-8 -*-
"""Day 1 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ka0E6xQheJtp0BHKcC8gcqXzmp7-m8YO
"""

a = int(input('Enter first no: '))
b = int(input('Enter the second no: '))

print('Sum:', a + b)